### ISSUE TITLE
Not working right now

### ISSUE THREAD

**Issue by Dehumanizer77** [viliampucik/nepi-jano#10]
nepi-jano stopped working about a week ago. Since it still works if you load the s.sme.sk with the article ID manually, I suppose just a small and simple fix will be enough to get it working again.

**Comment by viliampucik** [comment]
Please what is your add-on version and URLs that do not work? I tested from my end and all works fine with the latest version in Firefox.

**Comment by Dehumanizer77** [comment]
I have just checked and it works with Firefox 47, but does not work with Firefox 45.0.2, both with nepi jano version 1.2.2
Same URL http://domov.sme.sk/c/20194001/lesko-ak-kalinak-zvladne-basternaka-zvladol-by-aj-vrazdu-v-priamom-prenose.html?ref=tit

**Comment by viliampucik** [comment]
I have retested on my latest FIrefox 47 and Firefox ESR 45 and it works fine. The ESR version reguired restart for the add-on to work however. Do you still experience an issue or may I close this one?

**Comment by Dehumanizer77** [comment]
It works after restart, I haven't realised that I haven't restarted since the new version has been released, thank you.

**Comment by Buntaci** [comment]
Nepijano doesn't work on firefox 50 developer edition, but works on firefox android 50 and 51. Chrome without problem.

**Comment by viliampucik** [comment]
@Buntaci It works fine for me. Please provide more details such as the non working URL for further investigation.
