### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by havrancek** [viliampucik/nepi-jano#11]
http://tech.sme.sk/c/20279505/bijuce-srdce-pluta-pasca-na-chlad-ktora-vytvara-ladovce.html

**Comment by TomanPCM** [comment]
work fine.....

**Comment by havrancek** [comment]
not in firefox 49,0 x64

**Comment by havrancek** [comment]
is there a way to fix it? in FF 49 it´s not working at all
thx in advance

**Comment by kupony** [comment]
Aj mne to prestalo fungovat vo ff 49.

**Comment by viliampucik** [comment]
If you still have the issue please reinstall nepi-jano and it should work again.

Please let me know your results.

**Comment by havrancek** [comment]
i´ve done it, but nothing changed

**Comment by viliampucik** [comment]
OK, I have found the reason for the behavior and will try to fix it today.

In the meantime the workaround the current issue is to append `?piano_t=1` at the end of URL, for example http://tech.sme.sk/c/20279505/bijuce-srdce-pluta-pasca-na-chlad-ktora-vytvara-ladovce.html?piano_t=1

**Comment by havrancek** [comment]
thank you very much, can t wait

**Comment by viliampucik** [comment]
The new version has been submitted to Firefox Add-on Store for review and should appear soon.

In the meantime to read Piano articles please open their URLs with append `?piano_t=1` in New Private Windows.
