### ISSUE TITLE
Page keeps refreshing

### ISSUE THREAD

**Issue by mpitonak** [viliampucik/nepi-jano#14]
Locked pages keep refreshing in Chrome56/FF50.

**Comment by viliampucik** [comment]
Please can you provide more details such as URL example and what exactly is meant by locked page?

Just in case pleasy try to remove and install the extension from Chrome Store.

**Comment by moravcik** [comment]
same here, looks like every locked page is affected

**Comment by moravcik** [comment]
Console output attached
![selection_231](https://cloud.githubusercontent.com/assets/1102311/22396789/8840299c-e562-11e6-816b-95838206422b.jpg)

**Comment by viliampucik** [comment]
Thanks! Will look into it. Do you experiwnce the same with Firefox as well?

**Comment by moravcik** [comment]
It's the same on Firefox

**Comment by scholtzm** [comment]
Seems like the "trick" with `piano_t=1` no longer works.

**Comment by DanoL91** [comment]
Same on Opera 42.0.2393.517, Win10 x64
