### ISSUE TITLE
Nepijano opat nefunkcne (v3.0)

### ISSUE THREAD

**Issue by DanoL91** [viliampucik/nepi-jano#16]
Zda sa, ze najnovsia verzia nepijana (v3.0) je opat nefunkcna - po otvoreni inak zamknuteho clanku, je v spodnej casti text: 
"Tento článok vznikol exkluzívne pre SME. Prístup k všetkým článkom SME.sk si môžete kúpiť a pozrieť si ich mimo aplikácie, na naších web stránkach."

Priklad: https://tech.sme.sk/c/20461432/vedci-hovoria-ze-existuje-aj-siedmy-kontinent-nazvali-ho-zelandia.html

Win10, Opera 43.0

**Comment by spamovy** [comment]
Bud SME opat zmenilo URL, alebo konecne zaplatalo tu dieru a tym padom sme skoncili..

**Comment by PeterAndreus** [comment]
ich export URL prestala posielat cele clanky, posiela uz len skratene, takze aj cez nepi-jano sa objavia kratke..
Zda sa ze si to konecne fixli..
