### ISSUE TITLE
Nedaju sa prehravat videa

### ISSUE THREAD

**Issue by sveco86** [viliampucik/nepi-jano#19]
V zatvorenych clankoch sa nedaju prehrat videa, prehravac nefunguje - napr. https://domov.sme.sk/c/20659773/droba-zavadzal-o-apartmane-od-kocnera.html

**Comment by viliampucik** [comment]
Pridana funkcionalita na prehravanie videi v clankoch. Kedze Chrome zial nevie spolahlivo prehravat HD sme.sk videa, takze sa nacitava len ich SD variant. Kvalita medzi SD a HD je v pripade sme.sk zanedbatelna.
