### ISSUE TITLE
rel 0.11. firefox issue

### ISSUE THREAD

**Issue by mbajo** [viliampucik/nepi-jano#2]
doesn't work on: http://tech.sme.sk/c/20063521/sama-chyba-a-predsa-uspech-ako-dokazali-einsteinovu-teoriu.html

works fine e.g. on: http://tech.sme.sk/c/20063465/einstein-pridal-hmotu-a-radikalne-zmenil-svet-fyziky.html

**Comment by viliampucik** [comment]
You are correct. Sadly the mechanism for obtaining free version of paid articles, as described by in Miroslav Magda's blog post [Piano and SME.sk](http://blog.ejci.net/2013/04/21/piano-and-sme-sk/), does not work for the first URL and currently there is no workaround :(

**Comment by SelfMan** [comment]
The reason is that the SME page generator script throws an error:
Microsoft VBScript runtime error '800a0005'
Invalid procedure call or argument
/_cache.asp, line 87

The question is if its intentional or not. We'll see in the future.

**Comment by viliampucik** [comment]
The pained article has been released for free. Closing this one as no related issues has been reported so far.
