### ISSUE TITLE
[new feature] AdBlocker recognition

### ISSUE THREAD

**Issue by sveco86** [viliampucik/nepi-jano#20]
Nejedna sa o bug, ale Nepi-Jano by mohol obsahovat funkcionalitu vypnutia okna, ktore upozornuje na zapnuty AdBlocker.

![Screenshot](https://user-images.githubusercontent.com/427889/31004738-f1115b3c-a4f5-11e7-8a6b-dc9b9b62b1c0.png)

**Comment by viliampucik** [comment]
Skusal si namiesto AdBlock pouzit [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)? V mojom pripade mam totizto danu reklamu automaticky potlacenu.

Pre sme.sk sa aplikuju blokovacie filtre _uBlock filters_, _EasyList_, _EasyPrivacy_, _Fanboy’s Enhanced Tracking List, Peter Lowe’s Ad and tracking server list_ a _CZE, SVK: EasyList Czech and Slovak_.

**Comment by 4ndrej** [comment]
Toto nemá nepijano čo riešiť, na blokovanie reklamy je uBlock a podobné.
