### ISSUE TITLE
Nepi Jano - Chrome

### ISSUE THREAD

**Issue by ab021** [viliampucik/nepi-jano#21]
When installing an add-in to Chrome, it installs it, but when it starts again Chrome will block it with the add-on not from Google.

**Comment by timelordx** [comment]
That is a standard behaviour for any extension NOT installed from Google Web Store. You need to enable "Developer mode" in the top-right corner of the Extensions tab.

**Comment by viliampucik** [comment]
Please have you tried to install the extension from Google Store https://chrome.google.com/webstore/detail/nepi-jano/dmiebaglkdeebobffhbomapifjjjjakj?

**Comment by ab021** [comment]
Thanks
______________________________________________________________
> Od: Viliam Pucik <notifications@github.com>
> Komu: viliampucik/nepi-jano <nepi-jano@noreply.github.com>
> Dátum: 29.09.2017 23:12
> Predmet: Re: [viliampucik/nepi-jano] Nepi Jano - Chrome (#21)
>
Please have you tried to install the extension from Google Store https://chrome.google.com/webstore/detail/nepi-jano/dmiebaglkdeebobffhbomapifjjjjakj <https://chrome.google.com/webstore/detail/nepi-jano/dmiebaglkdeebobffhbomapifjjjjakj>?
