### ISSUE TITLE
rozsirenie o Dennik N?

### ISSUE THREAD

**Issue by sveco86** [viliampucik/nepi-jano#22]
Co tak rozsirit nepi-jano o Dennik N? Alebo vytvorit novy doplnok?

Zamknuty clanok: https://dennikn.sk/894697/po-bystrici-nitra-kde-sa-berie-panika-z-uhrika-a-preco-nitrianski-praviciari-zvazuju-volit-stareho-smeraka/
Full clanok je dostupny cez public api: https://dennikn.sk/api/reader?id=894697

ID clanku sa da dostat z url zamknuteho clanku

**Comment by viliampucik** [comment]
@sveco86: Klubuk dole! Velmi pekne dakujem za informaciu a vo velmi blizkej dobre sa do toho pustim. Navrhujem spravit radsej oddelene rozsirenie, lepsie sa bude maintainovat. Aky mu dame nazov?

**Comment by timelordx** [comment]
Majster N

**Comment by viliampucik** [comment]
@timelordx: Excelentne! :D Majster N ma veru dostal. Pustim sa co chvila do toho.

**Comment by viliampucik** [comment]
https://github.com/viliampucik/majster-n

**Comment by Ondriko** [comment]
už nepojde nikdy nepi jano! abo majser N hm pojde to niekedy????????
