### ISSUE TITLE
nefunguju "PREČÍTAJTE SI TIEŽ" odkazy

### ISSUE THREAD

**Issue by 4ndrej** [viliampucik/nepi-jano#23]
na stranke
https://profit.sme.sk/c/20648942/ako-prist-k-peniazom-a-neprerobit.html
je odkaz 

> PREČÍTAJTE SI TIEŽ:
> Frugal komunita: Chorobne šetria, aby mohli odísť v štyridsiatke na dôchodok

s linkou https://artemis.sme.sk/api/v2/article-header/20639174?ma_content=internal&ref=av-left

Linka nefunguje (vrati xml), funkcna linka je
https://ekonomika.sme.sk/c/20639174/frugal-komunita-chorobne-setria-aby-mohli-odist-v-styridsiatke-na-dochodok.html
Na tuto linku sa da dostat aj kratsim URL
https://ekonomika.sme.sk/c/20639174/

Cislo 20639174 je vsade rovnake, dalo by sa to nalinkovat cezen. HTML element je

> &lt;a class="article-avizo fl" href="https://artemis.sme.sk/api/v2/article-header/20639174?ma_content=internal&amp;ref=av-left"&gt;

asi by sa to dalo zakvacit na ten class "article-avizo"

**Comment by viliampucik** [comment]
Linka sice vrati XML, avsak v priebehu sekundy pride k presmerovaniu na spravnu stranku. Aspon tak to funguje na mojej strane.

Aky presne OS, prehliadac a verzia rozsirenia boli pouzite?

**Comment by 4ndrej** [comment]
runtime: google-chrome-beta-62.0.3202.45-1.x86_64/Fedora26/x86_64

Uz som na to prisiel.

Zozral to [RSS Subscription Extension (by Google)](https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd) a nepustil to dalej do toho automagickeho redirectu.

S vypnutym pozieracom RSS sa to automagicky redirectne na webUrl (&lt;webUrl&gt;https://ekonomika.sme.sk/c/20639174/frugal-komunita-chorobne-setria-aby-mohli-odist-v-styridsiatke-na-dochodok.html &lt;/webUrl&gt;) uvedene v tom xmlku (co je asi nejaka funkcia prehliadaca?).

To artemis xml url pride priamo s clankom z artemis.sme.sk/api, alebo je tam relativna adresa a nejako to poskladate v Nepijanovi?

**Comment by viliampucik** [comment]
Ano, URL na XML pride priamo z artemis.sme.sk/api, avsak mohol by som ju transparentne upravovat tak, aby ukazovala na genericku adresu https://sme.sk/c/CISLO_CLANKU/, ktora by uz sama presmerovala pouzivatela na prislusnu URL aj s poddomenou. Napriklad https://sme.sk/c/20639174/ je serverom presmerovana na https://ekonomika.sme.sk/c/20639174/frugal-komunita-chorobne-setria-aby-mohli-odist-v-styridsiatke-na-dochodok.html. Pojdem sa na to pozriet. A dakujem za podnetnu otazku :)

**Comment by 4ndrej** [comment]
Ak mozem tak hlasujem za on-the-fly prepisovanie na bazicke https://sme.sk/c/CISLO_CLANKU/ linky.

Artemis api si vracia svoje predzute linky, ale myslim ze Nepijano je filter html streamu urceneho pre browser a mal by takeho linky pre browser aj produkovat na vystupe. Nie je dobre spoliehat sa na automagicke (nedokumentovane) redirecty browserov.

**Comment by viliampucik** [comment]
Redirect na zaklade XML obsahu bolo v danom case jedine funkcne riesenie, kedze bazicke URL nefungovali. Suhlasim vsak, ze dozrel cas na zmenu :)

**Comment by viliampucik** [comment]
7e733a9f044b12e5880cfe8a9909bc602a92e8d8

**Comment by 4ndrej** [comment]
vdaka za link v prispievateloch
