### ISSUE TITLE
SME nefunguje

### ISSUE THREAD

**Issue by FellipeElRey** [viliampucik/nepi-jano#24]
Dobry den,
vsimol som si, ze rozsirenie na clanky SME nefunguje (chrome ani firefox). Mohli by ste sa na to pozriet?
Pr. na plateny clanok: https://tech.sme.sk/c/20104638/aj-vas-mozog-z-vas-robi-hlupaka-preco-nam-klame.html

Dakujem,
ako studentovi, co ma obmedzene vydavky, mi Vase rozsirenie velmi pomaha!

**Comment by malyd** [comment]
Aj mne prestalo fungovať rozšírenie vo FF. Verzia 4.3.

**Comment by scholtzm** [comment]
@viliampucik Publishnes aj v Chrome Store?

**Comment by viliampucik** [comment]
@scholtzm Velmi rad, avsak cakam na tretiu stranu, ktora to zabezpecuje.

**Comment by viliampucik** [comment]
@scholtzm  Uz by to malo byt.

**Comment by Dehumanizer77** [comment]
Uz zas to nejde, ten isty clanok napriklad.
