### ISSUE TITLE
Nepijano prestalo fungovať

### ISSUE THREAD

**Issue by duffysk** [viliampucik/nepi-jano#25]
Vo FF ani v Chrome nefunguje.

**Comment by TomanPCM** [comment]
co sa ozvali z Petit Pressu? ci iny dovod?

**Comment by viliampucik** [comment]
Iny dovod. Z dennikov sa nikto neozval.

**Comment by igorkulman** [comment]
Celkom by ma zaujímal ten dôvod. Určite nebol technický, lebo opraviť aby to znovu fungovalo je zmena 2 parametrov v URL.

**Comment by TomanPCM** [comment]
a bude nikto pokracovat?

**Comment by igorkulman** [comment]
Ak by chcel niekto pokračovať, tak stačí URL zmeniť z
````
https://artemis.sme.sk/api/v2/article/' + utils.articleId() + '?mid=0&fullcont=1&noAdverts=0&nightmode=0
````
na
````
https://artemis.sme.sk/api/v2/article/' + utils.articleId() + '?mid=10&fa=1&noAdverts=0&nightmode=0
````

(vyčítané z dekompilovaného Android APK).

Funguje to, mám to ako Firefox extension nainštalované lokálne ako ZIP sám pre seba ale nejak sa mi to nechce dávať verejne do Storu pod vlastným menom. Predsa je to taká šedá zóna.

**Comment by TomanPCM** [comment]
Jo funguje! dakujem! Ako do storu to nepatry, ale na githube by to bolo pekne ak by to niekto udrziaval.

**Comment by duffysk** [comment]
Asi nieco robim zle, zmenil som v article.js url ale nefunguje..

**Comment by TomanPCM** [comment]
ano, v article.js len nahradit, pod chrome to funguje

**Comment by elmooree** [comment]
potvrdzujem funkcnost. vdaka.

**Comment by havrancek** [comment]
vypol som FF, nahradil som text v xpi v profile FF, zapol FF a rozsirenie je fuc.. poprosim vas, mohli by ste mi poslat xpi subor pre FF? d.

**Comment by Dehumanizer77** [comment]
Treba si tu extension podpisat cez https://addons.mozilla.org/ , nepodpisane addony novy firefox neakceptuje. Ale staci si tam vytvorit account, uploadnut tam ten upraveny xpi, nastavit ze nebude publikovany, podpisat ho a potom stiahnut tu podpisanu verziu.

**Comment by duffysk** [comment]
Fungovala, ale dnes opat prestala.

**Comment by TomanPCM** [comment]
chrome pod win funfuje.....

**Comment by duffysk** [comment]
TomanPCM divne, mne FF ani Chrome na macOS nie, FF na Androide ano.

**Comment by igorkulman** [comment]
@duffysk  chyba je u teba, pretože tie linky (napr https://artemis.sme.sk/api/v2/article/20719693?mid=10&fa=1&noAdverts=0&nightmode=0) stále fungujú.

**Comment by duffysk** [comment]
@igorkulman mozne to je, pohrabem sa v tom, solved. Dakujem.

**Comment by diabolicek** [comment]
pomoze mi niekto to rozbehať?

**Comment by PeterAndreus** [comment]
Chrome rozsirenie:
https://github.com/PeterAndreus/nepi-jano
hodil som tam zmeny a skusil som na jednom clanku ci to funguje, je to ale nie moc udrziavana verzia a SME uz necitam, takze ak sa to rozbije asi to tak zostane
