### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by Dehumanizer77** [viliampucik/nepi-jano#3]
Previously the extension worked with videos as well, now it doesn't. The mechanism has changed and now you have to get an XML file which contains the URL of the video. I'm not sure if it's possible to update the page to actually play the video, but the video itself can be downloaded so it's just a matter of forcing the sme player to play the video URL. 
To get the video URL you need to download an XML located at http://www.sme.sk/storm/mmdata_get.asp?id=<video_id> (add &hd1=1 for HD version of the video) which then contains the video URL among other metadata.

**Comment by viliampucik** [comment]
Thanks for reporting this. Please do you have a particular article URL with video for testing?

**Comment by Dehumanizer77** [comment]
http://tv.sme.sk/v/31886/film-prvy-slovensky-horor.html
