### ISSUE TITLE
Firefox extension signing

### ISSUE THREAD

**Issue by marki555** [viliampucik/nepi-jano#5]
FF od verzie 43 zakaze nepodpisane extensions bez moznosti workaroundu (od 44). Treba sa zaregistrovat na addons.mozilla.org, kde sa da extension uploadnut a nechat automaticky podpisat (aj bez zverejnenia v zozname doplnkov).

Tu je k tomu viac info: https://wiki.mozilla.org/Addons/Extension_Signing

**Comment by viliampucik** [comment]
Ano, myslime na to :) Add-on uz vysse tyzdna caka na Mozilla Preliminary Review, podpisanie a zverejnenie: https://addons.mozilla.org/en-US/firefox/addon/nepi-jano/

**Comment by lukasprelovsky** [comment]
Ano, myslim ze je to stale aktualne :)  : http://screenshot.cz/MR/MRYSQ/spravca-doplnkov.png

**Comment by stevocz** [comment]
bude aj v chrome store? teraz je tam len povodna 0.10

**Comment by ghost** [comment]
Po aktualizacii staci ist do **_about:config_**, najst **_xpinstall.signatures.required_** a zmenit hodnotu na **_false_** :)

**Comment by 4ndrej** [comment]
@AdamMD to asi nebude velmi bezpecne nastavenie

**Comment by viliampucik** [comment]
@stevocz Chrome store vyzaduje jednorazovy poplatok $5 za zriadenie uctu na uploadovanie rozsireni vratane bezplatnych :( Z tohto dovodu ho neplanujem nahravat na Chrome store.

**Comment by marki555** [comment]
@AdamMD toto ide len vo verzii 43. Vo verzii 44 to zakazu uplne a podpis nebude vyzadovany iba pri nighlies buildoch FF, vo vsetkych ostatnych buldoch sa to nebude dat vypnut.
