### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by alfureu** [viliampucik/nepi-jano#7]
Please add Safari Extension.

**Comment by alfureu** [comment]
Sorry, was able to build a new extension based on your code. You can close this ticket.

**Comment by viliampucik** [comment]
I would like to publish Safari extension but it requires working Apple developer account which cost $99 per year.

**Comment by alfureu** [comment]
Yes and no. Anybody can build his/her own extension through the Develop Menu in Safari. So just please keep updating the this folder too.
